

CREATE TABLE IF NOT EXISTS VEHICLES (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    MAKE VARCHAR(50) NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    YEAR INTEGER NOT NULL,
    LAST_SCRAPE_DATE DATE
);

CREATE TABLE IF NOT EXISTS SOLD_LISTINGS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    YEAR INTEGER NOT NULL,
    MAKE VARCHAR(50) NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    SALEPRICE FLOAT,
    DATESOLD DATE
);

CREATE TABLE IF NOT EXISTS CURRENT_LISTINGS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    YEAR INTEGER NOT NULL,
    MAKE VARCHAR(50) NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    LISTPRICE FLOAT
);

CREATE TABLE IF NOT EXISTS SOLD_LISTING_STATS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    YEAR INTEGER NOT NULL,
    MAKE VARCHAR(50) NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    SALEPRICE FLOAT,
    AVG_SALE_PRICE FLOAT,
    MAX_SALE_PRICE FLOAT,
    LOW_SALE_PRICE FLOAT,
    MOVING_AVG FLOAT
);

CREATE TABLE IF NOT EXISTS CURRENT_LISTING_STATS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    YEAR INTEGER NOT NULL,
    MAKE VARCHAR(50) NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    LISTPRICE FLOAT, 
    VEHICLE_ID UUID
);




CREATE TABLE IF NOT EXISTS VEHICLES (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    MAKE VARCHAR(50) NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    YEAR INTEGER NOT NULL,
    LAST_SCRAPE_DATE DATE
);

CREATE TABLE IF NOT EXISTS SOLD_LISTINGS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    YEAR INTEGER NOT NULL,
    MAKE VARCHAR(50) NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    SALEPRICE FLOAT,
    DATESOLD DATE
);

CREATE TABLE IF NOT EXISTS CURRENT_LISTINGS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    YEAR INTEGER NOT NULL,
    MAKE VARCHAR(50) NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    LISTPRICE FLOAT
);

CREATE TABLE IF NOT EXISTS SOLD_LISTING_STATS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    YEAR INTEGER NOT NULL,
    MAKE VARCHAR(50) NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    SALEPRICE FLOAT,
    AVG_SALE_PRICE FLOAT,
    MAX_SALE_PRICE FLOAT,
    LOW_SALE_PRICE FLOAT,
    MOVING_AVG FLOAT
);

CREATE TABLE IF NOT EXISTS CURRENT_LISTING_STATS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    YEAR INTEGER NOT NULL,
    MAKE VARCHAR(50) NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    LISTPRICE FLOAT, 
    VEHICLE_ID UUID
);

