FROM node:16-alpine as react-build-step
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY frontend/my-app/package.json frontend/my-app/package-lock.json ./
COPY frontend/my-app/src ./src
COPY frontend/my-app/public ./public
RUN npm install
RUN npm run build

FROM nginx:stable-alpine
COPY --from=react-build-step /app/build /user/share/nginx/html

COPY nginx.default.conf /etc/nginx/conf.d/default.conf