FROM node:16-alpine as react-build-step
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY frontend/my-app/package.json  ./
COPY frontend/my-app/package-lock.json ./
COPY frontend/my-app/src ./src
COPY frontend/my-app/public ./public
RUN npm install
RUN npm run build && ls /app/build


# Run a command to keep the container alive
CMD ["tail", "-f", "/dev/null"]