FROM node:16-alpine as react-build-step
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY frontend/my-app/package.json  ./
COPY frontend/my-app/package-lock.json ./
COPY frontend/my-app/src ./src
COPY frontend/my-app/public ./public
RUN npm install
RUN npm run build

FROM nginx:stable-alpine
RUN apk update && apk add --no-cache nano

COPY --from=react-build-step /app/build /usr/share/nginx/html
COPY nginx.custom-gen.conf /etc/nginx/conf.d/default.conf

# Copy your SSL files
COPY nginx-config/server.crt /etc/nginx/ssl/server.crt
COPY nginx-config/server.key /etc/nginx/ssl/server.key
COPY nginx-config/fullchain.pem /etc/nginx/ssl/fullchain.pem

# Copy SSL configuration snippets
COPY nginx-config/ssl-params.conf /etc/nginx/ssl/ssl-params.conf

EXPOSE 80 443
